// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQnGWofQFNrZ0ZF__IKAli0WK4eMq0DKo',
    appId: '1:158415535434:android:70613af29f0a815e5c15b3',
    messagingSenderId: '158415535434',
    projectId: 'whatsapp-clone-flutter-1243f',
    storageBucket: 'whatsapp-clone-flutter-1243f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHEt6RTkfrP_bm3lTNnUrAXr4ZYH25jM',
    appId: '1:158415535434:ios:7a3425c4a2bc23805c15b3',
    messagingSenderId: '158415535434',
    projectId: 'whatsapp-clone-flutter-1243f',
    storageBucket: 'whatsapp-clone-flutter-1243f.appspot.com',
    iosClientId: '158415535434-bm7fpejn7to6101ja9607asc4m2btjma.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappcloneFlutter',
  );
}
